// Field catalog of a blank form: every AcroForm field (name, type, page, rect,
// maxLen, checkbox on-value, comb) joined with the XFA <speak> description when the
// form is a hybrid (plan section 6.3). Generated by scripts/forms/build-catalog.ts
// into data/forms/2025/catalog/<formId>.fields.json (committed); the registry test
// regenerates it from the blank PDF and fails if the committed copy drifts.

import {
  PDFArray,
  PDFButton,
  PDFCheckBox,
  PDFDict,
  PDFDocument,
  PDFDropdown,
  PDFHexString,
  PDFName,
  PDFOptionList,
  PDFRadioGroup,
  PDFRawStream,
  PDFSignature,
  PDFString,
  PDFTextField,
  decodePDFRawStream,
} from "pdf-lib";
import { scanXfaFields } from "@/lib/tax2025/pdf/xfa";

export type CatalogFieldType = "text" | "checkbox" | "radio" | "dropdown" | "optionlist" | "button" | "signature" | "other";

export interface CatalogRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface CatalogField {
  /** Full AcroForm field name; the key every map refers to. */
  name: string;
  type: CatalogFieldType;
  /** 0-based page index of the first widget, or null when it cannot be determined. */
  page: number | null;
  rect: CatalogRect | null;
  /** Text fields: maximum length, else null. */
  maxLen: number | null;
  /** Text fields: comb (one character per box). */
  comb: boolean;
  /** Checkboxes: the on-value name without the slash (e.g. "1"), else null. */
  onValue: string | null;
  /** XFA accessibility description joined by full name, else null. */
  speak: string | null;
}

export interface FormCatalog {
  formId: string;
  pages: number;
  fieldCount: number;
  /** True when the PDF carried an XFA packet (hybrid form). */
  hadXfa: boolean;
  /** XFA field names that are not AcroForm fields (harmless, e.g. Form 8949 has 1). */
  xfaOnlyFields: string[];
  /** AcroForm field names with no XFA twin. */
  acroOnlyFields: string[];
  fields: CatalogField[];
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function nameText(obj: unknown): string | null {
  if (obj instanceof PDFString || obj instanceof PDFHexString) return obj.decodeText();
  return null;
}

/** Decode the XFA `template` packet of a hybrid form, or null when there is no XFA. */
export function readXfaTemplate(doc: PDFDocument): string | null {
  const acro = doc.catalog.lookupMaybe(PDFName.of("AcroForm"), PDFDict);
  if (!acro) return null;
  const xfa = acro.lookup(PDFName.of("XFA"));
  if (xfa instanceof PDFArray) {
    for (let i = 0; i + 1 < xfa.size(); i += 2) {
      const label = nameText(xfa.lookup(i));
      if (label !== "template") continue;
      const stream = xfa.lookup(i + 1);
      if (stream instanceof PDFRawStream) {
        return new TextDecoder("utf-8").decode(decodePDFRawStream(stream).decode());
      }
    }
    return null;
  }
  if (xfa instanceof PDFRawStream) {
    // A single XFA stream holds the whole XDP; it is not used by the IRS forms but handle it.
    return new TextDecoder("utf-8").decode(decodePDFRawStream(xfa).decode());
  }
  return null;
}

export function hasXfa(doc: PDFDocument): boolean {
  const acro = doc.catalog.lookupMaybe(PDFName.of("AcroForm"), PDFDict);
  return !!acro && acro.has(PDFName.of("XFA"));
}

function fieldType(field: unknown): CatalogFieldType {
  if (field instanceof PDFTextField) return "text";
  if (field instanceof PDFCheckBox) return "checkbox";
  if (field instanceof PDFRadioGroup) return "radio";
  if (field instanceof PDFDropdown) return "dropdown";
  if (field instanceof PDFOptionList) return "optionlist";
  if (field instanceof PDFSignature) return "signature";
  if (field instanceof PDFButton) return "button";
  return "other";
}

/** Build the catalog of a blank form from its bytes. Reads XFA before pdf-lib's getForm() strips it. */
export async function buildCatalog(formId: string, bytes: Uint8Array): Promise<FormCatalog> {
  const doc = await PDFDocument.load(bytes, { updateMetadata: false });
  const hadXfa = hasXfa(doc);
  const template = readXfaTemplate(doc);
  const speakByName = new Map<string, string | null>();
  if (template !== null) {
    for (const f of scanXfaFields(template)) speakByName.set(f.name, f.speak);
  }

  // Page index of every widget annotation (by object reference).
  const pageOfRef = new Map<string, number>();
  doc.getPages().forEach((page, index) => {
    const annots = page.node.Annots();
    if (!annots) return;
    for (let k = 0; k < annots.size(); k++) {
      const ref = annots.get(k);
      pageOfRef.set(String(ref), index);
    }
  });

  const form = doc.getForm();
  const fields: CatalogField[] = [];
  for (const field of form.getFields()) {
    const type = fieldType(field);
    const widgets = field.acroField.getWidgets();
    const first = widgets[0];
    let page: number | null = null;
    let rect: CatalogRect | null = null;
    if (first) {
      const ref = doc.context.getObjectRef(first.dict);
      page = ref ? (pageOfRef.get(String(ref)) ?? null) : null;
      const r = first.getRectangle();
      rect = { x: round2(r.x), y: round2(r.y), width: round2(r.width), height: round2(r.height) };
    }
    let maxLen: number | null = null;
    let comb = false;
    let onValue: string | null = null;
    if (field instanceof PDFTextField) {
      maxLen = field.getMaxLength() ?? null;
      comb = field.isCombed();
    }
    if (field instanceof PDFCheckBox) {
      const on = field.acroField.getOnValue();
      onValue = on ? on.decodeText() : null;
    }
    const name = field.getName();
    fields.push({ name, type, page, rect, maxLen, comb, onValue, speak: speakByName.get(name) ?? null });
  }

  const acroNames = new Set(fields.map((f) => f.name));
  const xfaOnlyFields = [...speakByName.keys()].filter((n) => !acroNames.has(n)).sort();
  const acroOnlyFields = template === null ? [] : fields.map((f) => f.name).filter((n) => !speakByName.has(n)).sort();

  return {
    formId,
    pages: doc.getPageCount(),
    fieldCount: fields.length,
    hadXfa,
    xfaOnlyFields,
    acroOnlyFields,
    fields,
  };
}

/** Stable, diff-friendly serialisation: header keys indented, one line per field. */
export function serializeCatalog(catalog: FormCatalog): string {
  const { fields, ...header } = catalog;
  const head = JSON.stringify(header, null, 2).replace(/\n}$/, "");
  const lines = fields.map((f) => `    ${JSON.stringify(f)}`).join(",\n");
  return `${head},\n  "fields": [\n${lines}\n  ]\n}\n`;
}
