// Request handling for the TY2025 filled-PDF routes (plan section 6.10, task T6). The
// Next route files (app/api/tax/forms/[year]/pdf/**) do the auth() check as their very
// first statement and then call these functions with the authenticated user; keeping
// the logic here (a) lets Next's route files export only handlers and (b) lets the
// tests drive everything with an injected builder: no database, no network.
//
// Nothing is persisted (decision E4): the PDFs are built per request and streamed
// back. One AuditLog row (changeType "tax_packet_export") records WHICH forms and which
// return state (fingerprint) were exported; ids and counts only, never a value.
// Responses are never cacheable (private, no-store) because they carry tax data.

import { zipSync, type Zippable } from "fflate";
import { FORM_MAPS } from "@/lib/tax2025/pdf/maps";
import { fillFormCopies } from "@/lib/tax2025/pdf/copies";
import { formatNewYorkDate, shortFingerprint } from "@/lib/tax2025/pdf/format";
import { buildPacket } from "@/lib/tax2025/pdf/packet";
import { SUPPORTED_YEAR, isKnownFormId } from "@/lib/tax2025/pdf/registry";
import type { FormMap, PdfReturnView } from "@/lib/tax2025/pdf/types";

export const PACKET_EXPORT_CHANGE_TYPE = "tax_packet_export";

export interface PdfRouteUser {
  id: string;
  /** Display name, printed on the cover as "Generated by". */
  name: string;
}

/** What the audit row records: ids and counts only. */
export interface PacketExportAudit {
  userId: string;
  taxYear: 2025;
  kind: "packet" | "form";
  /** Form ids included. */
  forms: string[];
  stamp: boolean;
  /** Hex SHA-256 fingerprint of the return state. */
  fingerprint: string;
  engineVersion: string | null;
  openItemCount: number;
  fileCount: number;
}

export type BuiltView = { view: PdfReturnView } | { error: string };

export interface PdfRouteDeps {
  /** Builds the effective return view for the year (DB-aware in production, a stub in tests). */
  buildView: (year: 2025, generatedBy: string) => Promise<BuiltView>;
  /** Writes the AuditLog row. Rejects when the row cannot be written (the export is then refused). */
  recordExport: (entry: PacketExportAudit) => Promise<void>;
  /** Maps considered for the packet and servable as single forms. Default: every registered map. */
  maps?: readonly FormMap[];
}

type YearParse = { ok: true; year: 2025 } | { ok: false; status: 400 | 404; error: string };

/** Only the supported tax year is served; anything else is rejected before any work happens. */
export function parseYear(raw: string): YearParse {
  if (!/^\d{4}$/.test(raw)) return { ok: false, status: 400, error: "Invalid tax year." };
  if (Number(raw) !== SUPPORTED_YEAR) return { ok: false, status: 404, error: `Only tax year ${SUPPORTED_YEAR} is available.` };
  return { ok: true, year: SUPPORTED_YEAR };
}

/** `?stamp=0` asks for clean copies (no per-page DRAFT footer); anything else keeps the stamp (decision E1). */
export function parseStamp(raw: string | null): boolean {
  return raw !== "0";
}

/** Form ids that may be requested individually: registered maps whose blank form is in the manifest. */
export function servableFormIds(maps: readonly FormMap[]): string[] {
  return maps.map((m) => m.formId).filter((id) => isKnownFormId(id));
}

const NO_STORE = "private, no-store";

function jsonError(status: number, error: string): Response {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": NO_STORE },
  });
}

function fileResponse(bytes: Uint8Array, contentType: string, filename: string): Response {
  // Copy into a fresh ArrayBuffer-backed view so the body type is a plain BodyInit.
  const body = new Uint8Array(bytes);
  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(body.byteLength),
      "Cache-Control": NO_STORE,
    },
  });
}

/** Log only the error class: messages from the PDF/format layers can quote values. */
function logFailure(where: string, err: unknown): void {
  console.error(`[tax-pdf] ${where} failed: ${err instanceof Error ? err.name : "unknown error"}`);
}

export interface PacketRequest {
  year: string;
  /** Raw `stamp` query parameter. */
  stamp: string | null;
  user: PdfRouteUser;
}

export async function handlePacketRequest(req: PacketRequest, deps: PdfRouteDeps): Promise<Response> {
  const year = parseYear(req.year);
  if (!year.ok) return jsonError(year.status, year.error);
  const stamp = parseStamp(req.stamp);
  try {
    const built = await deps.buildView(year.year, req.user.name);
    if ("error" in built) return jsonError(500, built.error);
    const { view } = built;
    const packet = await buildPacket(view, { stamp, maps: deps.maps ?? FORM_MAPS });
    // A form filed in several copies (Form 8949) appears once in the audit row.
    const forms = [...new Set(packet.files.flatMap((f) => (f.formId === null ? [] : [f.formId])))];
    await deps.recordExport({
      userId: req.user.id,
      taxYear: year.year,
      kind: "packet",
      forms,
      stamp,
      fingerprint: view.fingerprint,
      engineVersion: view.engineVersion ?? null,
      openItemCount: view.openItems.length,
      fileCount: packet.files.length,
    });
    const name = `ty${year.year}-draft-packet-${shortFingerprint(view.fingerprint)}${stamp ? "" : "-clean"}.zip`;
    return fileResponse(packet.zip, "application/zip", name);
  } catch (err) {
    logFailure("packet", err);
    return jsonError(500, "The packet could not be built.");
  }
}

export interface FormRequest extends PacketRequest {
  form: string;
}

export async function handleFormRequest(req: FormRequest, deps: PdfRouteDeps): Promise<Response> {
  const year = parseYear(req.year);
  if (!year.ok) return jsonError(year.status, year.error);
  const maps = deps.maps ?? FORM_MAPS;
  // Whitelist: lowercase alphanumerics only, a registered map, and a manifest entry.
  const map = /^[a-z0-9]+$/.test(req.form) ? maps.find((m) => m.formId === req.form) : undefined;
  if (!map || !isKnownFormId(map.formId)) return jsonError(404, "Unknown form.");
  const stamp = parseStamp(req.stamp);
  try {
    const built = await deps.buildView(year.year, req.user.name);
    if ("error" in built) return jsonError(500, built.error);
    const { view } = built;
    const fp12 = shortFingerprint(view.fingerprint);
    // An explicitly requested form is filled even when the packet's inclusion rule would omit it.
    // A form filed in several copies (Form 8949) comes back as a zip with one PDF per copy.
    const sheets = await fillFormCopies(map.formId, view, map, {
      stamp,
      fingerprint: fp12,
      stampDate: formatNewYorkDate(view.generatedAt),
    });
    await deps.recordExport({
      userId: req.user.id,
      taxYear: year.year,
      kind: "form",
      forms: [map.formId],
      stamp,
      fingerprint: view.fingerprint,
      engineVersion: view.engineVersion ?? null,
      openItemCount: view.openItems.length,
      fileCount: sheets.length,
    });
    const only = sheets[0];
    if (sheets.length === 1 && only) {
      const name = `ty${year.year}-${map.formId}-${fp12}${stamp ? "" : "-clean"}.pdf`;
      return fileResponse(only.result.bytes, "application/pdf", name);
    }
    const mtime = new Date(view.generatedAt);
    const zippable: Zippable = {};
    sheets.forEach(({ copy, result }, i) => {
      zippable[`${map.formId}-${copy?.suffix ?? String(i + 1)}.pdf`] = [result.bytes, { mtime, level: 0 }];
    });
    return fileResponse(zipSync(zippable), "application/zip", `ty${year.year}-${map.formId}-${fp12}${stamp ? "" : "-clean"}.zip`);
  } catch (err) {
    logFailure(`form ${map.formId}`, err);
    return jsonError(500, "The form could not be built.");
  }
}
