// Request handling for the TY2025 filled-PDF routes (plan section 6.10, task T6). The
// Next route files (app/api/tax/forms/[year]/pdf/**) do the auth() check as their very
// first statement and then call these functions with the authenticated user; keeping
// the logic here (a) lets Next's route files export only handlers and (b) lets the
// tests drive everything with an injected builder: no database, no network.
//
// Nothing is persisted (decision E4): the PDFs are built per request and streamed
// back. One AuditLog row (changeType "tax_packet_export") records WHICH forms and which
// return state (fingerprint) were exported; ids and counts only, never a value.
// Responses are never cacheable (private, no-store) because they carry tax data.
//
// Clean copies are gated (ai-return-reviewer A5): `?stamp=0` and `?final=1` return 403 unless the owner's approval for the
// CURRENT return fingerprint exists (deps.approval; the default is "no approval"). `?final=1` returns the final package
// (final-package.ts), or one clean form with neutral properties on the single-form route. The stamped draft is always served.

import { zipSync, type Zippable } from "fflate";
import { FORM_MAPS } from "@/lib/tax2025/pdf/maps";
import { fillFormCopies } from "@/lib/tax2025/pdf/copies";
import { formatNewYorkDate, shortFingerprint } from "@/lib/tax2025/pdf/format";
import { buildFinalPackage } from "@/lib/tax2025/pdf/final-package";
import { buildPacket } from "@/lib/tax2025/pdf/packet";
import { SUPPORTED_YEAR, isKnownFormId, sha256Hex } from "@/lib/tax2025/pdf/registry";
import type { FormMap, PdfReturnView } from "@/lib/tax2025/pdf/types";
import { CLEAN_COPY_REFUSED, noApprovalLookup, type ApprovalLookup } from "@/lib/tax2025-pdf-approval";

export const PACKET_EXPORT_CHANGE_TYPE = "tax_packet_export";
/** The AuditLog changeType of a final-package download (fingerprint, file count and the sha256 of each file; never a value). */
export const FINAL_PACKAGE_CHANGE_TYPE = "tax_final_package_download";

export interface PdfRouteUser {
  id: string;
  /** Display name, printed on the cover as "Generated by". */
  name: string;
}

/** What the audit row records: ids and counts only. */
export interface PacketExportAudit {
  userId: string;
  taxYear: 2025;
  kind: "packet" | "form" | "final";
  /** Form ids included. */
  forms: string[];
  stamp: boolean;
  /** Hex SHA-256 fingerprint of the return state. */
  fingerprint: string;
  engineVersion: string | null;
  openItemCount: number;
  /** How many overrides (line figures, decisions, acknowledgements) were in force: a count, never a value or a reason. */
  overrideCount: number;
  fileCount: number;
  /** Final package / final form only: hex SHA-256 of each file by name (hashes identify the bytes; they carry no value). */
  fileSha256?: Record<string, string>;
}

export type BuiltView = { view: PdfReturnView } | { error: string };

export interface PdfRouteDeps {
  /** Builds the effective return view for the year (DB-aware in production, a stub in tests). */
  buildView: (year: 2025, generatedBy: string) => Promise<BuiltView>;
  /** Writes the AuditLog row. Rejects when the row cannot be written (the export is then refused). */
  recordExport: (entry: PacketExportAudit) => Promise<void>;
  /** Maps considered for the packet and servable as single forms. Default: every registered map. */
  maps?: readonly FormMap[];
  /** Owner-approval lookup for clean copies / the final package. Default: nothing is approved (every clean copy is refused). */
  approval?: ApprovalLookup;
}

type YearParse = { ok: true; year: 2025 } | { ok: false; status: 400 | 404; error: string };

/** Only the supported tax year is served; anything else is rejected before any work happens. */
export function parseYear(raw: string): YearParse {
  if (!/^\d{4}$/.test(raw)) return { ok: false, status: 400, error: "Invalid tax year." };
  if (Number(raw) !== SUPPORTED_YEAR) return { ok: false, status: 404, error: `Only tax year ${SUPPORTED_YEAR} is available.` };
  return { ok: true, year: SUPPORTED_YEAR };
}

/** `?stamp=0` asks for clean copies (no per-page DRAFT footer); anything else keeps the stamp (decision E1). */
export function parseStamp(raw: string | null): boolean {
  return raw !== "0";
}

/** `?final=1` asks for the final package (or one final form). Anything else is not a final request. */
export function parseFinal(raw: string | null): boolean {
  return raw === "1";
}

/**
 * Whether the owner's approval exists for `fingerprint`. A lookup that fails counts as "not approved" (fail closed): the
 * caller answers 403, never a clean copy.
 */
async function isApproved(deps: PdfRouteDeps, fingerprint: string): Promise<boolean> {
  try {
    return await (deps.approval ?? noApprovalLookup).currentApproval(fingerprint);
  } catch (err) {
    logFailure("approval lookup", err);
    return false;
  }
}

/** When the approval for `fingerprint` was recorded, for the package index. Best effort: any failure leaves the date out (the approval itself was already checked). */
async function approvedAtOf(deps: PdfRouteDeps, fingerprint: string): Promise<string | null> {
  try {
    return (await deps.approval?.approvedAt?.(fingerprint)) ?? null;
  } catch (err) {
    logFailure("approval date lookup", err);
    return null;
  }
}

/** Form ids that may be requested individually: registered maps whose blank form is in the manifest. */
export function servableFormIds(maps: readonly FormMap[]): string[] {
  return maps.map((m) => m.formId).filter((id) => isKnownFormId(id));
}

const NO_STORE = "private, no-store";

function jsonError(status: number, error: string): Response {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": NO_STORE },
  });
}

function fileResponse(bytes: Uint8Array, contentType: string, filename: string): Response {
  // Copy into a fresh ArrayBuffer-backed view so the body type is a plain BodyInit.
  const body = new Uint8Array(bytes);
  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(body.byteLength),
      "Cache-Control": NO_STORE,
    },
  });
}

/** Log only the error class: messages from the PDF/format layers can quote values. */
function logFailure(where: string, err: unknown): void {
  console.error(`[tax-pdf] ${where} failed: ${err instanceof Error ? err.name : "unknown error"}`);
}

export interface PacketRequest {
  year: string;
  /** Raw `stamp` query parameter. */
  stamp: string | null;
  /** Raw `final` query parameter ("1" = the final package / a final form). */
  final?: string | null;
  user: PdfRouteUser;
}

function hashFiles(files: ReadonlyArray<{ name: string; bytes: Uint8Array }>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const f of files) out[f.name] = sha256Hex(f.bytes);
  return out;
}

export async function handlePacketRequest(req: PacketRequest, deps: PdfRouteDeps): Promise<Response> {
  const year = parseYear(req.year);
  if (!year.ok) return jsonError(year.status, year.error);
  const final = parseFinal(req.final ?? null);
  const stamp = final ? false : parseStamp(req.stamp);
  try {
    const built = await deps.buildView(year.year, req.user.name);
    if ("error" in built) return jsonError(500, built.error);
    const { view } = built;
    // Clean copies (no per-page DRAFT footer) and the final package exist only for an approved return.
    if ((!stamp || final) && !(await isApproved(deps, view.fingerprint))) return jsonError(403, CLEAN_COPY_REFUSED);
    if (final) return await handleFinalPackage(view, req, deps);
    const packet = await buildPacket(view, { stamp, maps: deps.maps ?? FORM_MAPS });
    // A form filed in several copies (Form 8949) appears once in the audit row.
    const forms = [...new Set(packet.files.flatMap((f) => (f.formId === null ? [] : [f.formId])))];
    await deps.recordExport({
      userId: req.user.id,
      taxYear: year.year,
      kind: "packet",
      forms,
      stamp,
      fingerprint: view.fingerprint,
      engineVersion: view.engineVersion ?? null,
      openItemCount: view.openItems.length,
      overrideCount: view.overrideNotice.count,
      fileCount: packet.files.length,
    });
    const name = `ty${year.year}-draft-packet-${shortFingerprint(view.fingerprint)}${stamp ? "" : "-clean"}.zip`;
    return fileResponse(packet.zip, "application/zip", name);
  } catch (err) {
    logFailure("packet", err);
    return jsonError(500, "The packet could not be built.");
  }
}

/** The final package for an approved return (the caller has already checked the approval for this fingerprint). */
async function handleFinalPackage(view: PdfReturnView, req: PacketRequest, deps: PdfRouteDeps): Promise<Response> {
  // Defence in depth: an approval is bound to a return with no blocking item, so a blocking item here means the approval is not for this state.
  if (view.openItems.some((i) => i.severity === "blocking")) {
    return jsonError(409, "The final package is not built while blocking items remain.");
  }
  const result = await buildFinalPackage(view, { maps: deps.maps ?? FORM_MAPS, approvedAt: await approvedAtOf(deps, view.fingerprint) });
  if (!result.ok) return jsonError(409, `The final package could not be built: ${result.reason}`);
  await deps.recordExport({
    userId: req.user.id,
    taxYear: 2025,
    kind: "final",
    forms: result.forms,
    stamp: false,
    fingerprint: view.fingerprint,
    engineVersion: view.engineVersion ?? null,
    openItemCount: view.openItems.length,
    overrideCount: view.overrideNotice.count,
    fileCount: result.files.length,
    fileSha256: hashFiles(result.files),
  });
  return fileResponse(result.zip, "application/zip", `ty${view.taxYear}-final-${shortFingerprint(view.fingerprint)}.zip`);
}

export interface FormRequest extends PacketRequest {
  form: string;
}

export async function handleFormRequest(req: FormRequest, deps: PdfRouteDeps): Promise<Response> {
  const year = parseYear(req.year);
  if (!year.ok) return jsonError(year.status, year.error);
  const maps = deps.maps ?? FORM_MAPS;
  // Whitelist: lowercase alphanumerics only, a registered map, and a manifest entry.
  const map = /^[a-z0-9]+$/.test(req.form) ? maps.find((m) => m.formId === req.form) : undefined;
  if (!map || !isKnownFormId(map.formId)) return jsonError(404, "Unknown form.");
  const final = parseFinal(req.final ?? null);
  const stamp = final ? false : parseStamp(req.stamp);
  try {
    const built = await deps.buildView(year.year, req.user.name);
    if ("error" in built) return jsonError(500, built.error);
    const { view } = built;
    if ((!stamp || final) && !(await isApproved(deps, view.fingerprint))) return jsonError(403, CLEAN_COPY_REFUSED);
    const fp12 = shortFingerprint(view.fingerprint);
    // An explicitly requested form is filled even when the packet's inclusion rule would omit it.
    // A form filed in several copies (Form 8949) comes back as a zip with one PDF per copy.
    const sheets = await fillFormCopies(map.formId, view, map, {
      stamp,
      fingerprint: fp12,
      stampDate: formatNewYorkDate(view.generatedAt),
      ...(final ? { final: true } : {}),
    });
    await deps.recordExport({
      userId: req.user.id,
      taxYear: year.year,
      kind: final ? "final" : "form",
      forms: [map.formId],
      stamp,
      fingerprint: view.fingerprint,
      engineVersion: view.engineVersion ?? null,
      openItemCount: view.openItems.length,
      overrideCount: view.overrideNotice.count,
      fileCount: sheets.length,
      ...(final ? { fileSha256: hashFiles(sheets.map((s, i) => ({ name: `${map.formId}-${s.copy?.suffix ?? String(i + 1)}.pdf`, bytes: s.result.bytes }))) } : {}),
    });
    const tag = final ? "-final" : stamp ? "" : "-clean";
    const only = sheets[0];
    if (sheets.length === 1 && only) {
      const name = `ty${year.year}-${map.formId}-${fp12}${tag}.pdf`;
      return fileResponse(only.result.bytes, "application/pdf", name);
    }
    const mtime = new Date(view.generatedAt);
    const zippable: Zippable = {};
    sheets.forEach(({ copy, result }, i) => {
      zippable[`${map.formId}-${copy?.suffix ?? String(i + 1)}.pdf`] = [result.bytes, { mtime, level: 0 }];
    });
    return fileResponse(zipSync(zippable), "application/zip", `ty${year.year}-${map.formId}-${fp12}${tag}.zip`);
  } catch (err) {
    logFailure(`form ${map.formId}`, err);
    return jsonError(500, "The form could not be built.");
  }
}
