// The TY2025 seed for the tax facts store (tax-facts-carry-forward-store).
//
// Every entry is transcribed from `specs/12-owner-confirmed-facts-ty2025.md` and nothing else. The anti-fabrication
// guard: each entry carries a `specAnchor` (and optionally more) that must be a verbatim substring of that file;
// `lib/__tests__/tax-facts-seed.test.ts` reads the spec and fails if one is missing. If the spec's wording changes, the
// entry must be re-read and re-anchored, never paraphrased into existence.
//
// What is deliberately NOT seeded: any dollar amount a document holds (W-2, interest, dividends, brokerage, Form 1098
// and property-tax amounts, the Seacoast and Fox Farm W-2 figures, the estate 1099-INT interest, the IRA contribution on
// the Betterment 5498), the 2026 donation log entry (the Donation log is its system of record), the 2025 opening IRA
// basis (superseded by the closing figure below), and any recorded none-statement answers (those are TY2025 return
// inputs). The only dollar figures kept are the derived IRA basis closing figure and the owner's own renovation
// estimate. No SSN, EIN, account number or date of birth appears here.
//
// Policy defaults: `stable` only for historical or structurally permanent facts, `year_specific` for events or
// statements of one year, `derived` for the IRA basis closing figure, and `reconfirm` whenever there is any doubt.
//
// PURE data: no DB, no network, no clock.

import type { CarryPolicy, FactCategory, FactValueKind, SourceKind } from "@/lib/tax-facts/types";

export const TAX_FACTS_SEED_VERSION = 1;

/** Spec 12's own status line is dated 2026-10-07: the day the owner confirmed these facts. */
export const TAX_FACTS_SEED_CONFIRMED_AT = new Date("2026-10-07T16:00:00.000Z");

export interface SeedFact {
  factKey: string;
  category: FactCategory;
  label: string;
  valueKind: FactValueKind;
  valueCents?: number;
  valueText?: string;
  carryPolicy: CarryPolicy;
  sourceKind: SourceKind;
  /** A pointer to the place in spec 12 (no values). */
  sourceRef: string;
  /** The tax year the fact was established for (2025 unless the spec says otherwise). */
  taxYear: number;
  /** Optional reason text carried from the spec (decisions only). */
  reason?: string;
  /** A verbatim substring of specs/12-owner-confirmed-facts-ty2025.md that this entry is transcribed from. */
  specAnchor: string;
  /** More verbatim substrings when the value draws on several sentences. */
  moreAnchors?: readonly string[];
}

const HH = "specs/12, Household and roles";
const INC = "specs/12, Income documents";
const SCC = "specs/12, EK Consulting and decisions";
const RET = "specs/12, Retirement, donations, payments";
const HOMES = "specs/12, Homes";
const EST = "specs/12, Estate";
const OPEN = "specs/12, Open items";

export const TAX_FACTS_SEED_TY2025: readonly SeedFact[] = [
  // ── household ──
  {
    factKey: "household.filing_status",
    category: "household",
    label: "Filing status",
    valueKind: "choice",
    valueText: "mfj",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HH}, bullet 1`,
    taxYear: 2025,
    specAnchor: "Joint (MFJ) return",
  },
  {
    factKey: "household.children_dependents",
    category: "household",
    label: "Children and dependents",
    valueKind: "none_statement",
    valueText: "No children, no dependents",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HH}, bullet 1`,
    taxYear: 2025,
    specAnchor: "No children, no electric vehicle, no dependents",
  },
  {
    factKey: "household.electric_vehicle",
    category: "household",
    label: "Electric vehicle",
    valueKind: "none_statement",
    valueText: "No electric vehicle",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HH}, bullet 1`,
    taxYear: 2025,
    specAnchor: "No children, no electric vehicle, no dependents",
  },
  {
    factKey: "household.preparer",
    category: "household",
    label: "Who prepares the return",
    valueKind: "text",
    valueText: "Eric is the self-preparer of record; no paid review wanted",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HH}, bullet 1`,
    taxYear: 2025,
    specAnchor: "Eric is the self-preparer of record",
    moreAnchors: ["no paid review wanted"],
  },

  // ── business ──
  {
    factKey: "business.ekc.material_participation",
    category: "business",
    label: "Eric materially participates in Eric Kinniburgh Consulting, LLC (Schedule C)",
    valueKind: "bool",
    valueText: "yes",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HH}, bullet 2`,
    taxYear: 2025,
    specAnchor: "Eric materially participates in Eric Kinniburgh Consulting, LLC",
  },
  {
    factKey: "business.sudden_valley.formed",
    category: "business",
    label: "Sudden Valley Property Management LLC formation",
    valueKind: "text",
    valueText: "Formed February 2026 (not a 2025 item)",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${HH}, bullet 2`,
    taxYear: 2026,
    specAnchor: "Sudden Valley Property Management LLC was formed Feb 2026 (not a 2025 item)",
  },
  {
    factKey: "business.mezzo.status",
    category: "business",
    label: "Mezzo",
    valueKind: "text",
    valueText: "Not formed; left out of discussions until the owner adds it manually",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HH}, bullet 2`,
    taxYear: 2025,
    specAnchor: "Mezzo is not formed and is left out of discussions until the owner adds it manually",
  },
  {
    factKey: "business.ekc.software_expenses_all_llc",
    category: "business",
    label: "Software expenses are all for the LLC",
    valueKind: "bool",
    valueText: "yes",
    carryPolicy: "year_specific",
    sourceKind: "owner_statement",
    sourceRef: `${SCC}, bullet 1`,
    taxYear: 2025,
    specAnchor: "Software expenses are all for the LLC and 2025",
  },
  {
    factKey: "business.ekc.depreciable_items",
    category: "business",
    label: "Depreciable items and de minimis statement",
    valueKind: "none_statement",
    valueText: "Nothing to depreciate; no de minimis safe-harbor statement",
    carryPolicy: "year_specific",
    sourceKind: "owner_statement",
    sourceRef: `${SCC}, bullet 1`,
    taxYear: 2025,
    specAnchor: "nothing to depreciate, no de minimis safe-harbor statement",
  },
  {
    factKey: "business.ekc.mileage",
    category: "business",
    label: "Business mileage",
    valueKind: "none_statement",
    valueText: "No 2025 business mileage",
    carryPolicy: "year_specific",
    sourceKind: "owner_statement",
    sourceRef: `${SCC}, bullet 1`,
    taxYear: 2025,
    specAnchor: "No 2025 business mileage",
  },
  {
    factKey: "business.ekc.se_health_or_retirement_plan",
    category: "business",
    label: "Self-employed health insurance or retirement plan",
    valueKind: "none_statement",
    valueText: "No SE health insurance or SE retirement plan",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${SCC}, bullet 1`,
    taxYear: 2025,
    specAnchor: "No SE health insurance or SE retirement plan",
  },

  // ── income ──
  {
    factKey: "income.taxpayer_m.employers",
    category: "income",
    label: "Eric's employers",
    valueKind: "text",
    valueText: "Two employers through PEOs (Rippling PEO 1 and TriNet HR III)",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${INC}, bullet 1`,
    taxYear: 2025,
    specAnchor: "Eric: two employers through PEOs (Rippling PEO 1 and TriNet HR III)",
  },
  {
    factKey: "income.taxpayer_f.employers",
    category: "income",
    label: "Eva-Laura's employers",
    valueKind: "text",
    valueText: "Seacoast Mushrooms and Fox Farm Brewery",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${INC}, bullet 1`,
    taxYear: 2025,
    specAnchor: "Seacoast Mushrooms",
    moreAnchors: ["Fox Farm Brewery"],
  },
  {
    factKey: "income.taxpayer_f.tipped_occupation",
    category: "income",
    label: "Eva-Laura's tipped occupation",
    valueKind: "text",
    valueText: "Fox Farm Brewery: job on the IRS tipped-occupation list",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${INC}, bullet 1`,
    taxYear: 2025,
    specAnchor: "job on the IRS tipped-occupation list",
    moreAnchors: ["Fox Farm Brewery"],
  },
  {
    factKey: "income.taxpayer_f.overtime_flsa",
    category: "income",
    label: "Eva-Laura's overtime status",
    valueKind: "text",
    valueText: "Seacoast Mushrooms: FLSA-covered, non-exempt employee (owner statement)",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${INC}, bullet 1`,
    taxYear: 2025,
    specAnchor: "FLSA-covered, non-exempt employee, owner statement",
    moreAnchors: ["Seacoast Mushrooms"],
  },
  {
    factKey: "income.other_information_returns",
    category: "income",
    label: "Other information returns (1099-NEC, 1099-MISC, 1099-K)",
    valueKind: "none_statement",
    valueText: "No 1099-NEC/MISC/K beyond the documents",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${INC}, bullet 2`,
    taxYear: 2025,
    specAnchor: "No 1099-NEC/MISC/K beyond the documents",
  },
  {
    factKey: "income.broker_carryover_adjustments",
    category: "income",
    label: "Brokerage carryovers and other adjustments",
    valueKind: "none_statement",
    valueText: "No carryover from 2024, no other broker adjustments",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${INC}, bullet 3`,
    taxYear: 2025,
    specAnchor: "No carryover from 2024, no other broker adjustments",
  },
  {
    factKey: "income.margin_or_investment_interest",
    category: "income",
    label: "Margin or investment interest",
    valueKind: "none_statement",
    valueText: "No margin or investment interest",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${RET}, bullet 3`,
    taxYear: 2025,
    specAnchor: "No margin or investment interest",
  },

  // ── payments ──
  {
    factKey: "payments.estimated_federal_ct",
    category: "payments",
    label: "Estimated payments and prior-year overpayment applied",
    valueKind: "none_statement",
    valueText: "No federal or CT estimated payments for 2025; no 2024 overpayment applied; no 2024 CT balance paid",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${RET}, bullet 3`,
    taxYear: 2025,
    specAnchor: "No federal or CT estimated payments for 2025; no 2024 overpayment applied; no 2024 CT balance paid",
  },

  // ── decisions (recall-only copies; the return uses the decisions recorded on the Forms page) ──
  {
    factKey: "decision.x1.home_office_method",
    category: "decision",
    label: "X1 Home office method",
    valueKind: "choice",
    valueText: "simplified",
    carryPolicy: "reconfirm",
    sourceKind: "decision",
    sourceRef: `${SCC}, bullet 2 (X1)`,
    taxYear: 2025,
    reason: "A 2025 loss allows nothing either way; revisit for 2026 if profitable",
    specAnchor: "X1 home office = simplified (a 2025 loss allows nothing either way; revisit for 2026 if profitable)",
  },
  {
    factKey: "decision.x5.arbor_rd_property_tax",
    category: "decision",
    label: "X5 56 Arbor Rd property tax",
    valueKind: "choice",
    valueText: "schedule_a",
    carryPolicy: "reconfirm",
    sourceKind: "decision",
    sourceRef: `${SCC}, bullet 2 (X5)`,
    taxYear: 2025,
    specAnchor: "X5 56 Arbor Rd property tax = deduct on Schedule A",
  },
  {
    factKey: "decision.x6.internet_phone_business_pct",
    category: "decision",
    label: "X6 Internet & Phone business share",
    valueKind: "percent",
    valueText: "50",
    carryPolicy: "reconfirm",
    sourceKind: "decision",
    sourceRef: `${SCC}, bullet 2 (X6)`,
    taxYear: 2025,
    reason: "Owner statement, no document",
    specAnchor: "X6 Internet & Phone business share = 50% (owner statement, no document)",
  },
  {
    factKey: "decision.x7.federal_overpayment",
    category: "decision",
    label: "X7 Federal overpayment",
    valueKind: "choice",
    valueText: "refund_all",
    carryPolicy: "reconfirm",
    sourceKind: "decision",
    sourceRef: `${SCC}, bullet 2 (X7)`,
    taxYear: 2025,
    specAnchor: "X7 federal overpayment = refund all",
  },
  {
    factKey: "decision.x8.ct_overpayment",
    category: "decision",
    label: "X8 Connecticut overpayment",
    valueKind: "choice",
    valueText: "refund_all",
    carryPolicy: "reconfirm",
    sourceKind: "decision",
    sourceRef: `${SCC}, bullet 2 (X8)`,
    taxYear: 2025,
    reason: "No CHET, no charity contribution; bank lines are hand-entered",
    specAnchor: "X8 CT overpayment = refund all (no CHET, no charity contribution; bank lines are hand-entered)",
  },

  // ── retirement ──
  {
    factKey: "retirement.taxpayer_m.ira_basis_end",
    category: "retirement",
    label: "Eric's traditional IRA basis carried to 2026 (end of 2025)",
    valueKind: "money_cents",
    valueCents: 1_430_000,
    carryPolicy: "derived",
    sourceKind: "derived",
    sourceRef: `${RET}, bullet 1`,
    taxYear: 2025,
    specAnchor: "basis carried to 2026 is 14,300",
  },
  {
    factKey: "retirement.taxpayer_m.ira_2025_contribution",
    category: "retirement",
    label: "Eric's 2025 traditional IRA contribution",
    valueKind: "text",
    valueText: "Traditional IRA contribution (Eric) made in 2025, nondeductible (amount per the TY2025 documents)",
    carryPolicy: "year_specific",
    sourceKind: "owner_statement",
    sourceRef: `${RET}, bullet 1`,
    taxYear: 2025,
    specAnchor: "traditional IRA contribution (Eric) made in 2025, nondeductible",
  },
  {
    factKey: "retirement.taxpayer_f.covered_by_workplace_plan",
    category: "retirement",
    label: "Eva-Laura is covered by a workplace retirement plan",
    valueKind: "bool",
    valueText: "yes",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${RET}, bullet 1`,
    taxYear: 2025,
    specAnchor: "Eva-Laura is covered at work",
  },

  // ── property ──
  {
    factKey: "property.old_barry_rd_27.use",
    category: "property",
    label: "27 Old Barry Rd use",
    valueKind: "text",
    valueText: "Primary residence",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 1`,
    taxYear: 2025,
    specAnchor: "27 Old Barry Rd (primary residence)",
  },
  {
    factKey: "property.old_barry_rd_27.mortgage_purpose",
    category: "property",
    label: "27 Old Barry Rd mortgage purpose",
    valueKind: "text",
    valueText: "The PennyMac loan on the Form 1098 bought the home (home acquisition debt)",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 1`,
    taxYear: 2025,
    specAnchor: "the PennyMac loan on the Form 1098 bought it (home acquisition debt",
  },
  {
    factKey: "property.old_barry_rd_27.solar",
    category: "property",
    label: "27 Old Barry Rd solar",
    valueKind: "text",
    valueText: "Solar installed 2022 with the credit already taken",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 1`,
    taxYear: 2025,
    specAnchor: "solar installed 2022 with the credit already taken",
  },
  {
    factKey: "property.arbor_rd_56.ownership",
    category: "property",
    label: "56 Arbor Rd ownership history",
    valueKind: "text",
    valueText:
      "A warranty deed filed with the town in March 2019 gave Eva-Laura a 90% joint tenancy (right of survivorship) with her mother; her mother died August 2024 and Eva-Laura became the sole beneficiary; probate completed December 2025",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 2`,
    taxYear: 2025,
    specAnchor:
      "a warranty deed filed with the town in March 2019 gave Eva-Laura a 90% joint tenancy (right of survivorship) with her mother",
    moreAnchors: ["her mother died August 2024 and Eva-Laura became the sole beneficiary; probate completed December 2025"],
  },
  {
    factKey: "property.arbor_rd_56.deed_not_gift",
    category: "property",
    label: "56 Arbor Rd 2019 deed was not a gift",
    valueKind: "text",
    valueText: "The 2019 deed was not a gift (owner statement)",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 2`,
    taxYear: 2025,
    specAnchor: "The 2019 deed was not a gift (owner statement)",
  },
  {
    factKey: "property.arbor_rd_56.use",
    category: "property",
    label: "56 Arbor Rd use",
    valueKind: "text",
    valueText: "Personal second home in 2025; short-term rental (stays under 7 days) through Sudden Valley only from April 2026",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 2`,
    taxYear: 2025,
    specAnchor: "Personal second home in 2025; short-term rental (stays under 7 days) through Sudden Valley only from April 2026",
  },
  {
    factKey: "property.arbor_rd_56.no_mortgage",
    category: "property",
    label: "56 Arbor Rd has no mortgage",
    valueKind: "bool",
    valueText: "yes",
    carryPolicy: "reconfirm",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 2`,
    taxYear: 2025,
    specAnchor: "second home, no mortgage",
  },
  {
    factKey: "property.arbor_rd_56.renovations_capitalized",
    category: "property",
    label: "56 Arbor Rd 2025 renovations",
    valueKind: "text",
    valueText: "About 90,000 of 2025 renovations paid with estate cash are capital improvements (not deducted)",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 2`,
    taxYear: 2025,
    specAnchor: "About 90,000 of 2025 renovations paid with estate cash are capital improvements (not deducted)",
  },

  // ── estate ──
  {
    factKey: "estate.executor_and_sole_beneficiary",
    category: "estate",
    label: "Estate: executor and sole beneficiary",
    valueKind: "text",
    valueText: "Eva-Laura is executor and sole beneficiary",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${EST}, bullet 1`,
    taxYear: 2025,
    specAnchor: "Eva-Laura is executor and sole beneficiary",
  },
  {
    factKey: "estate.has_own_ein",
    category: "estate",
    label: "The estate has its own EIN (the number itself is never stored)",
    valueKind: "bool",
    valueText: "yes",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${EST}, bullet 1`,
    taxYear: 2025,
    specAnchor: "the estate has its own EIN",
  },
  {
    factKey: "estate.form_1041_2024_filed",
    category: "estate",
    label: "Estate 2024 Form 1041",
    valueKind: "text",
    valueText:
      "The estate's 2024 Form 1041 was filed: no bond interest (the bonds had not been cashed), no Schedule K-1 ever issued",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${EST}, bullet 1`,
    taxYear: 2025,
    specAnchor:
      "The estate's 2024 Form 1041 was filed: no bond interest (the bonds had not been cashed), no Schedule K-1 ever issued",
  },
  {
    factKey: "estate.no_final_2024_form_1040_for_mother",
    category: "estate",
    label: "Final 2024 Form 1040 for the mother",
    valueKind: "text",
    valueText: "No final 2024 Form 1040 was filed for the mother",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${EST}, bullet 1`,
    taxYear: 2025,
    specAnchor: "No final 2024 Form 1040 was filed for the mother",
  },
  {
    factKey: "estate.bond_interest_2025_reporting_decision",
    category: "estate",
    label: "2025 estate savings-bond interest: how it is reported",
    valueKind: "text",
    valueText: "Decision (2026-10-07): report the 2025 estate savings-bond interest on the 2025 joint return as interest passing from the estate",
    carryPolicy: "year_specific",
    sourceKind: "owner_statement",
    sourceRef: `${EST}, bullet 2`,
    taxYear: 2025,
    specAnchor: "Decision (2026-10-07): report the",
    moreAnchors: ["on the 2025 joint return as interest passing from the estate"],
  },

  // ── open items (carried until the owner resolves them; never facts) ──
  {
    factKey: "open.estate_2025_form_1041_and_k1",
    category: "open_item",
    label: "Estate 2025 Form 1041 and K-1",
    valueKind: "open_item",
    valueText: "Estate 2025 Form 1041 and K-1 for the 2025 savings-bond interest (probably late; the app cannot build a 1041)",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: OPEN,
    taxYear: 2025,
    specAnchor: "Estate 2025 Form 1041 and K-1 for",
    moreAnchors: ["(probably late; the app cannot build a 1041)"],
  },
  {
    factKey: "open.estate_2024_1041_period_and_final_1040",
    category: "open_item",
    label: "Estate 2024 Form 1041 period and a final 2024 Form 1040",
    valueKind: "open_item",
    valueText:
      "The 2024 Form 1041 period (an estate's first year normally starts at the date of death) and whether the mother needed a final 2024 Form 1040",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: OPEN,
    taxYear: 2025,
    specAnchor:
      "the 2024 Form 1041 period (an estate's first year normally starts at the date of death) and whether the mother needed a final 2024 Form 1040",
  },
  {
    factKey: "open.arbor_rd_2019_deed_gift_tax",
    category: "open_item",
    label: "56 Arbor Rd 2019 deed gift-tax question",
    valueKind: "open_item",
    valueText: "The 2019 deed gift-tax question: whether a gift tax return was needed",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: OPEN,
    taxYear: 2025,
    specAnchor: "the 2019 deed gift-tax question",
    moreAnchors: ["whether a gift tax return was needed is OPEN"],
  },
  {
    factKey: "open.arbor_rd_basis_for_depreciation",
    category: "open_item",
    label: "56 Arbor Rd basis for 2026 depreciation",
    valueKind: "open_item",
    valueText: "The basis of 56 Arbor Rd for 2026 depreciation",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: OPEN,
    taxYear: 2025,
    specAnchor: "the basis of 56 Arbor Rd for 2026 depreciation",
  },
  {
    factKey: "open.seacoast_flsa_confirmation",
    category: "open_item",
    label: "Seacoast written confirmation of the FLSA overtime premium",
    valueKind: "open_item",
    valueText: "Written confirmation from Seacoast that the W-2 box 14 overtime premium is FLSA overtime premium",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: OPEN,
    taxYear: 2025,
    specAnchor: "written confirmation from Seacoast that the",
    moreAnchors: ["is FLSA overtime premium"],
  },
  {
    factKey: "open.ct_line_39_vs_ct1041_k1",
    category: "open_item",
    label: "Re-check CT line 39 against a Schedule CT-1041 K-1",
    valueKind: "open_item",
    valueText: "Re-check CT line 39 against a Schedule CT-1041 K-1 when it exists",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: OPEN,
    taxYear: 2025,
    specAnchor: "re-check CT line 39 against a Schedule CT-1041 K-1 when it exists",
  },
  {
    factKey: "open.barn_office_foodlab_depreciation",
    category: "open_item",
    label: "Barn office / food-lab structure: depreciation and Form 8829",
    valueKind: "open_item",
    valueText: "A barn office / food-lab structure: depreciation and Form 8829 are a 2026+ question",
    carryPolicy: "stable",
    sourceKind: "owner_statement",
    sourceRef: `${HOMES}, bullet 1`,
    taxYear: 2025,
    specAnchor: "A barn office / food-lab structure: depreciation and Form 8829 are a 2026+ question",
  },
];
