import { PDFDocument } from "pdf-lib";
import { describe, expect, it } from "vitest";
import { buildCoverModel, renderCover, type CoverBlock, type CoverForm, type CoverInput } from "@/lib/tax2025/pdf/cover";
import type { PacketOpenItem } from "@/lib/tax2025/pdf/types";
import { INCOMPLETE_HEADLINE, makeOpenItems, makeView } from "./fixtures/tax2025-pdf-view.fixture";

const forms: CoverForm[] = [
  { formId: "f1040", title: "Form 1040", included: true, reason: "Form 1040 is always included", blankByDesign: { ssn: 4, bank: 5, owner_statement_na: 52 } },
  { formId: "f1040s2", title: "Schedule 2", included: false, reason: "every mapped line is not applicable, zero or not yet computed", blankByDesign: {} },
];

function text(blocks: CoverBlock[]): string[] {
  return blocks.map((b) => (b.kind === "kv" ? `${b.label}: ${b.value}` : b.kind === "spacer" ? "" : b.text));
}

function input(over: Partial<CoverInput> = {}): CoverInput {
  return { view: makeView(), forms, fillItems: [], continuations: [], stamp: true, ...over };
}

describe("cover model", () => {
  it("states the DRAFT framing, timestamp in America/New_York, fingerprint and generator", () => {
    const lines = text(buildCoverModel(input()).blocks);
    expect(lines[0]).toMatch(/^DRAFT - computed for CPA review - not a filed return$/);
    expect(lines.some((l) => l === "Generated: 2026-10-03 22:30 EDT")).toBe(true);
    expect(lines.some((l) => l === "Generated by: Test Runner (synthetic)")).toBe(true);
    const model = buildCoverModel(input());
    expect(lines.some((l) => l === `Return fingerprint: ${model.fingerprint12}`)).toBe(true);
    expect(model.fingerprint12).toHaveLength(12);
    expect(lines.some((l) => /CPA is the preparer of record/.test(l))).toBe(true);
    expect(lines.some((l) => /a blank is zero/.test(l))).toBe(true);
    expect(lines.some((l) => /never shown as 0/.test(l))).toBe(true);
  });

  it("complete headline prints the numbers; negative balance is a refund", () => {
    const lines = text(buildCoverModel(input()).blocks);
    expect(lines).toContain("Federal AGI: $96,734");
    expect(lines).toContain("Federal balance (positive = owed, negative = refund): $-1,500");
    expect(lines.some((l) => l.startsWith("PROVISIONAL"))).toBe(false);
  });

  it("incomplete headline prints ONLY the provisional estimate, clearly labelled, with the assumed-zero lines", () => {
    const lines = text(buildCoverModel(input({ view: makeView({ headline: INCOMPLETE_HEADLINE }) })).blocks);
    expect(lines.some((l) => l.startsWith("PROVISIONAL - the return is not complete"))).toBe(true);
    expect(lines).toContain("PROVISIONAL: these lines were treated as $0: f1040.2b, sch1.3");
    expect(lines).toContain("Provisional federal total tax: $8,000");
    expect(lines.some((l) => l.startsWith("Federal AGI:"))).toBe(false);
    expect(lines).toContain("Blocking items: 2");
  });

  it("lists included and omitted forms with reasons", () => {
    const lines = text(buildCoverModel(input()).blocks);
    expect(lines.some((l) => l.startsWith("Form 1040 (f1040) - included"))).toBe(true);
    expect(lines.some((l) => l.startsWith("Schedule 2 (f1040s2) - omitted: every mapped line"))).toBe(true);
  });

  it("every engine open item appears exactly once, blocking first, with its action; duplicates by id collapse", () => {
    const items = makeOpenItems(60);
    const view = makeView({ openItems: [...items, items[0]!] });
    const lines = text(buildCoverModel(input({ view })).blocks);
    for (const i of items) {
      const hits = lines.filter((l) => l.includes(i.message));
      expect(hits, i.id).toHaveLength(1);
      expect(hits[0]).toContain(i.action);
    }
    const firstAdvisory = lines.findIndex((l) => l.startsWith("- ") === false && l.startsWith("[ADVISORY]"));
    const lastBlocking = lines.map((l) => l.startsWith("[BLOCKING]")).lastIndexOf(true);
    expect(lastBlocking).toBeLessThan(firstAdvisory);
    expect(lines.some((l) => l === "Open items for CPA (40 blocking, 20 advisory)")).toBe(true);
  });

  it("fill items split into blank lines and fill notes, each once", () => {
    const fill: PacketOpenItem[] = [
      { id: "blank:f1040:f1040.2b", severity: "blocking", source: "line_blank", formId: "f1040", message: "Form 1040 line 2b (Taxable interest): left blank - missing" },
      { id: "blank:f1040:f1040.2b", severity: "blocking", source: "line_blank", formId: "f1040", message: "Form 1040 line 2b (Taxable interest): left blank - missing" },
      { id: "fill:f1040:namesplit", severity: "advisory", source: "fill", formId: "f1040", message: "verify the split" },
    ];
    const lines = text(buildCoverModel(input({ fillItems: fill })).blocks);
    expect(lines.filter((l) => l.includes("left blank - missing"))).toHaveLength(1);
    expect(lines).toContain("Lines left blank on the forms (1)");
    expect(lines).toContain("Fill notes (1)");
  });

  it("lists overrides, stale overrides, defaults and decisions", () => {
    const view = makeView({
      overrides: [
        { key: "sch1.3", formLabel: "Schedule 1", formLine: "3", note: "CPA override: was $1 computed, now $2", stale: false },
        { key: "f1040.10", formLabel: "Form 1040", formLine: "10", note: "CPA override: was $5 computed, now $9", stale: true },
      ],
      decisions: [
        { id: "X1", label: "Home office method", chosen: "simplified", status: "default_undecided", effectNote: "actual method would change tax by $X" },
        { id: "X3", label: "QBI form", chosen: "8995", status: "decided", decidedBy: "Eric", decidedAt: "2026-10-05" },
      ],
      acknowledged: ["qbi-8995"],
    });
    const lines = text(buildCoverModel(input({ view })).blocks);
    expect(lines).toContain("Schedule 1 line 3: CPA override: was $1 computed, now $2");
    expect(lines).toContain("Stale overrides (re-confirm or clear)");
    expect(lines).toContain("Form 1040 line 10: CPA override: was $5 computed, now $9");
    expect(lines).toContain("Home office method: simplified (default, undecided) - actual method would change tax by $X");
    expect(lines).toContain("QBI form: 8995 - decided by Eric on 2026-10-05");
    expect(lines).toContain("qbi-8995");
  });

  it("lists what is left blank by design per form, and the citations", () => {
    const lines = text(buildCoverModel(input()).blocks);
    expect(lines.some((l) => l.startsWith("Form 1040: Social security numbers: 4; Bank routing / account numbers: 5"))).toBe(true);
    expect(lines).toContain("fed.std_deduction_mfj_2025, fed.brackets_mfj_2025");
  });

  it("continuation lists every row", () => {
    const rows = Array.from({ length: 16 }, (_, i) => ({ payer: `Bank ${i + 1}`, amount: (i + 1) * 10 }));
    const lines = text(buildCoverModel(input({ continuations: [{ formId: "f1040sb", table: "schb.interest", rows }] })).blocks);
    expect(lines).toContain("Continuation: schb.interest (f1040sb), all 16 rows");
    expect(lines.filter((l) => /^\d+\. payer: Bank/.test(l))).toHaveLength(16);
    expect(lines).toContain("16. payer: Bank 16 | amount: $160");
  });
});

describe("cover rendering", () => {
  it("a 60-item fixture renders at least 2 pages and loads back", async () => {
    const view = makeView({ openItems: makeOpenItems(60) });
    const model = buildCoverModel(input({ view }));
    const { bytes, pageCount } = await renderCover(model);
    expect(pageCount).toBeGreaterThanOrEqual(2);
    const doc = await PDFDocument.load(bytes);
    expect(doc.getPageCount()).toBe(pageCount);
  });

  it("never throws on non-WinAnsi text or very long unbroken tokens", async () => {
    const view = makeView({
      openItems: [
        {
          id: "x",
          severity: "blocking",
          formLabel: "Form 1040",
          lineKeys: [],
          message: `Payer “José” 😀 ${"A".repeat(400)}`,
          action: "中文 action",
        },
      ],
    });
    const { pageCount } = await renderCover(buildCoverModel(input({ view })));
    expect(pageCount).toBeGreaterThanOrEqual(1);
  });

  it("a minimal return is a single cover page", async () => {
    const { pageCount } = await renderCover(buildCoverModel(input({ forms: [] })));
    expect(pageCount).toBeGreaterThanOrEqual(1);
  });
});
