// The six Return-completeness questions added for CT-1040 Schedule 1 (ty2025-mip-ct-schedule1): generated by the
// existing none-group loop, no questionnaire version bump, so saved answers are not marked stale.
import { describe, expect, it } from "vitest";
import { buildCardState, renderCopy, validateDefinition, visibleNodes, UNSURE_ID, type AnswerValue, type EffectiveAnswers } from "@/lib/tax-questionnaire";
import { RC_NONE_GROUP_IDS, RETURN_COMPLETENESS_ID, SOURCE_IDS, questionnaireById } from "@/lib/tax-questionnaire-content";
import { RC_CONTEXT, parseCompletenessAnswers } from "@/lib/tax2025/answers";
import { NONE_GROUP_IDS, NONE_GROUP_TEXT } from "@/lib/tax2025/line-catalog";
import { CT_SCH1_GROUPS } from "@/lib/tax2025/rules/ct-schedule1";

const def = questionnaireById(RETURN_COMPLETENESS_ID)!;
const PEOPLE = [
  { userId: "u-eric", name: "Eric Kinniburgh" },
  { userId: "u-eva", name: "Eva-Laura Ramirez-Wisiackas" },
];
const NEW_GROUPS = ["ct_muni_bonds", "ct_us_gov_funds", "ct_chet_able", "ct_prior_addbacks", "ct_other_additions", "ct_other_subtractions"] as const;
const when = "2026-10-04T12:00:00.000Z";

function answers(values: Record<string, AnswerValue>): EffectiveAnswers {
  const eff: EffectiveAnswers = {};
  for (const [id, value] of Object.entries(values)) eff[id] = { value, source: "questionnaire", at: when, by: "u-eric" };
  return eff;
}

describe("the six CT Schedule 1 groups", () => {
  it("are the rule's groups and are registered as none groups with statement text", () => {
    expect([...CT_SCH1_GROUPS]).toEqual([...NEW_GROUPS]);
    for (const g of NEW_GROUPS) {
      expect(NONE_GROUP_IDS).toContain(g);
      expect(RC_NONE_GROUP_IDS).toContain(g);
      expect(NONE_GROUP_TEXT[g].length, g).toBeGreaterThan(30);
    }
  });

  it("each has a g_ question (Yes / No / Not sure) and a ga_ amount node shown only after Yes, placed after the capital-gain questions", () => {
    const ids = def.nodes.map((n) => n.id);
    const lastCapital = ids.indexOf("ga_capital_special_rates");
    expect(lastCapital).toBeGreaterThan(0);
    for (const g of NEW_GROUPS) {
      const q = def.nodes.find((n) => n.id === `g_${g}`);
      expect(q, g).toBeDefined();
      expect(ids.indexOf(`g_${g}`), g).toBeGreaterThan(lastCapital);
      if (q?.kind !== "single") throw new Error("not a single-choice node");
      expect(q.options.map((o) => o.id)).toEqual(["some", "none", UNSURE_ID]);
      expect(q.showWhen).toBeNull();
      const ga = def.nodes.find((n) => n.id === `ga_${g}`);
      expect(ga?.kind).toBe("dollars");
      expect(JSON.stringify(ga?.showWhen)).toContain(`g_${g}`);
      expect(JSON.stringify(ga?.showWhen)).toContain("some");
    }
  });

  it("the prompts are unique, plain language (acronyms spelled out), question-shaped and leave no unresolved placeholder", () => {
    const prompts = def.nodes.filter((n) => n.id.startsWith("g_")).map((n) => n.prompt);
    expect(new Set(prompts).size).toBe(prompts.length);
    const newPrompts = NEW_GROUPS.map((g) => renderCopy(def.nodes.find((n) => n.id === `g_${g}`)!.prompt, RC_CONTEXT));
    for (const p of newPrompts) {
      expect(p.endsWith(")") || p.endsWith("?"), p).toBe(true);
      expect(p, p).not.toMatch(/\{[^}]*\}/);
    }
    const all = newPrompts.join(" ");
    // acronyms are spelled out at their first use
    expect(all).toContain("Connecticut Higher Education Trust (CHET)");
    expect(all).toContain("Achieving a Better Life Experience (ABLE)");
    expect(all).toContain("exchange-traded fund (ETF");
    expect(all).toContain("Treasury bill (T-bill)");
    // year-aware wording: the year comes from the context, never hard-coded inside the phrase
    expect(renderCopy(def.nodes.find((n) => n.id === "g_ct_prior_addbacks")!.prompt, { year: 2025, entityName: null })).toContain("four years before 2025");
    expect(renderCopy(def.nodes.find((n) => n.id === "g_ct_prior_addbacks")!.prompt, { year: 2026, entityName: null })).toContain("four years before 2026");
    // (the generic template prefix "In 2025, did Eric or Eva ..." predates this task and is not year-aware: recorded as an open item)
    const phrase = def.nodes.find((n) => n.id === "g_ct_prior_addbacks")!.prompt.replace(/^In 2025, did Eric or Eva have any of these: /, "");
    expect(phrase).not.toMatch(/\b20\d\d\b/);
    expect(phrase).toContain("{year}");
  });

  it("the definition still validates and is still version 2 (no bump: saved answers are not stale)", () => {
    expect(validateDefinition(def, SOURCE_IDS)).toEqual([]);
    expect(def.version).toBe(2);
  });

  it("a saved answers row written before these questions is not marked stale; the new questions simply show as unanswered", () => {
    const stored: Record<string, { v: AnswerValue; at: string; by: string }> = {};
    for (const n of def.nodes) {
      if (NEW_GROUPS.some((g) => n.id === `g_${g}` || n.id === `ga_${g}`)) continue;
      stored[n.id] = { v: n.kind === "single" ? (n.options.find((o) => o.id === "none")?.id ?? n.options[0]!.id) : n.kind === "multi" ? [n.options[0]!.id] : 0, at: when, by: "u-eric" };
    }
    const card = buildCardState(def, "household", RC_CONTEXT, { taxYear: 2025, entityId: "household", questionnaireId: def.id, definitionVersion: 2, answers: stored, note: null }, []);
    expect(card.stale).toBe(false);
    const visible = visibleNodes(def, RC_CONTEXT, answers({}));
    for (const g of NEW_GROUPS) expect(visible.map((n) => n.id)).toContain(`g_${g}`);
  });
});

describe("parseCompletenessAnswers with the new groups", () => {
  const base: Record<string, AnswerValue> = {};
  for (const g of NEW_GROUPS) base[`g_${g}`] = "none";

  it("six 'No' answers -> six statedNone true", () => {
    const p = parseCompletenessAnswers(answers(base), PEOPLE);
    for (const g of NEW_GROUPS) expect(p.statedNone[g], g).toBe(true);
  });
  it("a Yes with an amount is a stated false carrying the amount; Not sure leaves the group absent", () => {
    const p = parseCompletenessAnswers(answers({ ...base, g_ct_chet_able: "some", ga_ct_chet_able: 250_000, g_ct_muni_bonds: UNSURE_ID }), PEOPLE);
    expect(p.statedNone.ct_chet_able).toBe(false);
    expect(p.returnAnswers.statedSomeAmounts.ct_chet_able?.value).toBe(250_000);
    expect(p.statedNone.ct_muni_bonds).toBeUndefined();
    expect(p.statedNone.ct_us_gov_funds).toBe(true);
  });
  it("answers saved before the groups existed parse without the new ids (nothing is assumed)", () => {
    const p = parseCompletenessAnswers(answers({ g_other_taxes: "none" }), PEOPLE);
    for (const g of NEW_GROUPS) expect(p.statedNone[g], g).toBeUndefined();
    expect(p.statedNone.other_taxes).toBe(true);
  });
});
